[[pages]]
path = "app.py"
name = "Welcome"
icon = "ğŸ‘‹"

[[pages]]
path = "sidebar_pages/standings.py"
name = "Standings"
icon = "ğŸ“‹"

[[pages]]
path = "sidebar_pages/scores.py"
name = "Scores"
icon = "ğŸ¯"

[[pages]]
path = "sidebar_pages/schedule.py"
name = "Schedule"
icon = "ğŸ—“ï¸"

[[pages]]
path = "sidebar_pages/stat_leaders.py"
name = "Stat Leaders"
icon = "ğŸ“Š"
