[[pages]]
path = "app.py"
name = "Welcome"
icon = "ğŸ‘‹"

[[pages]]
path = "sidebar_pages/standings.py"
name = "Standings"
icon = "ğŸ“‹"

[[pages]]
path = "sidebar_pages/scores.py"
name = "Scores"
icon = "ğŸ¯"